// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmqrN614AwDqzZQtIU4BHu39V4ZOhppt0',
    appId: '1:206883213986:web:5f9583d7a3a2de7e2cbdfb',
    messagingSenderId: '206883213986',
    projectId: 'docsmanager-d4666',
    authDomain: 'docsmanager-d4666.firebaseapp.com',
    databaseURL: 'https://docsmanager-d4666-default-rtdb.firebaseio.com',
    storageBucket: 'docsmanager-d4666.appspot.com',
    measurementId: 'G-QH5KN39F07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsfGwahckxHoFgo23vmdxSDE4CrGuHbdc',
    appId: '1:206883213986:android:6796adeace6e01302cbdfb',
    messagingSenderId: '206883213986',
    projectId: 'docsmanager-d4666',
    databaseURL: 'https://docsmanager-d4666-default-rtdb.firebaseio.com',
    storageBucket: 'docsmanager-d4666.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCziZOi3J4H6xSbII-HOwUH3Pujw9SQ8Hs',
    appId: '1:206883213986:ios:287b4fd1976587932cbdfb',
    messagingSenderId: '206883213986',
    projectId: 'docsmanager-d4666',
    databaseURL: 'https://docsmanager-d4666-default-rtdb.firebaseio.com',
    storageBucket: 'docsmanager-d4666.appspot.com',
    iosClientId: '206883213986-a0hdjdalip157odl4ti6ar7g2rgf0qod.apps.googleusercontent.com',
    iosBundleId: 'com.DIMA.dox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCziZOi3J4H6xSbII-HOwUH3Pujw9SQ8Hs',
    appId: '1:206883213986:ios:3811e1ab1e4fe0562cbdfb',
    messagingSenderId: '206883213986',
    projectId: 'docsmanager-d4666',
    databaseURL: 'https://docsmanager-d4666-default-rtdb.firebaseio.com',
    storageBucket: 'docsmanager-d4666.appspot.com',
    iosClientId: '206883213986-d5007sr3o1328e560goi1msufb37lcgm.apps.googleusercontent.com',
    iosBundleId: 'com.example.docsManager',
  );
}
